# Generated by Django 3.2.5 on 2021-08-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='venue',
            new_name='venue_of_operation',
        ),
    ]
