# Generated by Django 3.2.5 on 2021-08-15 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_appointment_request_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=200)),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=200)),
                ('review', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='appointment_request',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment_request',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment_request',
            name='second_opinion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment_request',
            name='sent_to_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
        migrations.AddField(
            model_name='patient_rating',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.appointment_request'),
        ),
        migrations.AddField(
            model_name='doctor_rating',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.appointment_request'),
        ),
    ]
