# Generated by Django 3.2.5 on 2021-08-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20210815_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='insurance',
            field=models.CharField(default=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='insurance2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='insurance3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='insurance4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='insurance5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
