# Generated by Django 3.2.5 on 2021-08-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20210816_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_request',
            name='cancelled_by_patient',
            field=models.BooleanField(default=False),
        ),
    ]
