# Generated by Django 3.2.5 on 2021-08-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_appointment_request_cancelled_by_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default=False, max_length=200),
            preserve_default=False,
        ),
    ]
