# Generated by Django 3.2.5 on 2021-08-16 19:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_doctor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Second_Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date_second', models.DateField(default=django.utils.timezone.now)),
                ('seen_second', models.BooleanField(default=False)),
                ('accepted_second', models.BooleanField(default=False)),
                ('cancelled_second', models.BooleanField(default=False)),
                ('cancelled_by_patient_second', models.BooleanField(default=False)),
                ('sent_to_pa_secondtient_second', models.BooleanField(default=False)),
                ('doctor_app_second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_second', to='patient.doctor')),
                ('patient_app_second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_second', to='patient.patient')),
            ],
        ),
    ]
