# Generated by Django 3.2.5 on 2021-08-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_second_opinion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='second_opinion',
            old_name='sent_to_pa_secondtient_second',
            new_name='sent_to_patient_second',
        ),
    ]
