# Generated by Django 3.2.5 on 2021-08-17 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Rating_Second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_second', models.CharField(max_length=200)),
                ('review_second', models.TextField()),
                ('appointment_second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.second_opinion')),
            ],
        ),
    ]
