# Generated by Django 3.2.5 on 2021-08-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_patient_rating_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='appointment_feedback',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='second_opinion_feedback',
        ),
        migrations.DeleteModel(
            name='Doctor_Rating',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
