# Generated by Django 3.2.5 on 2021-08-17 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_auto_20210817_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_second', models.TextField()),
                ('notes_second', models.TextField()),
                ('second_opinion_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.second_opinion')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField()),
                ('notes', models.TextField()),
                ('appointment_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.appointment_request')),
            ],
        ),
    ]
